default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flashcards_development

test:
  <<: *default
  database: flashcards_test

production:
  <<: *default
  database: flashcards_production
